spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/resource_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    exchange-name: "book-exchange"
    queue-name: "book-logs"
    routing-key: "book.events"

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

server:
  port: 8080

SWAGGER_API_VERSION: 1.0.0
